### ISSUE TITLE
No way to cross check if the image got built via the pipeline

### ISSUE THREAD

**Issue by tuxdna** [containscafeine/data-model#12]
After the recent pull request that was merged : https://github.com/containscafeine/data-model/pull/11

I can't figure out if the image was actually built. How can this be resolved?

I suppose a Github integration with Container Pipeline should be enough -- something that marks the github repo with an Image build update message.

**Comment by tuxdna** [comment]
@containscafeine @vpavlin Any suggestions for this resolving this issue?

**Comment by tuxdna** [comment]
`+` @mohammedzee1000

**Comment by concaf** [comment]
Well, that could be done if we get access to the build logs for CCCP, or if CCCP send a status to GitHub (webhooks, etc), "IIRC" I don't think either of the things happen right now.

How about sending an email to a broader mailing list for now?

**Comment by tuxdna** [comment]
@containscafeine Is there already a mailing list setup for CCCP builds ? That way I could join it, and will be enough to get the notifications.

**Comment by concaf** [comment]
@tuxdna I don't think so there is one, but we can set it to send emails to you, or someone else from the team, or to your mailing list?

**Comment by tuxdna** [comment]
@containscafeine Sending an email to me, sounds fine too. Just that it creates a dependency on me notifying.

@miteshvp Would you like to be added as well ?

**Comment by concaf** [comment]
@tuxdna can you send a PR to change the emails mentioned in https://github.com/CentOS/container-index/blob/master/index.d/datamodel.yml for the 3 `notify-email` fields?

**Comment by miteshvp** [comment]
Yes @tuxdna , that would be great. Atleast we are abreast of what is happening.

**Comment by tuxdna** [comment]
@containscafeine @miteshvp This PR got merged - https://github.com/CentOS/container-index/pull/114

So hopefully if everything goes right, we should be able to get notifications for image builds.

**Comment by miteshvp** [comment]
Sounds Good.

**Comment by miteshvp** [comment]
Getting regular updates around the builds via email. Hence closing this issue.
