### ISSUE TITLE
Make Read and Write units configurable

### ISSUE THREAD

**Issue by miteshvp** [containscafeine/data-model#20]
dynamodb.properties file gives the flexibility of configuring read and write units. Please make it configurable with a default value of 25.

1. Make following values in dynamodb.properties file
storage.dynamodb.stores.edgestore.capacity-read=25
storage.dynamodb.stores.edgestore.capacity-write=25
storage.dynamodb.stores.graphindex.capacity-read=25
storage.dynamodb.stores.graphindex.capacity-write=25

2. If an environment variable is provided, use that value instead of above default ones.

**Comment by tuxdna** [comment]
Closed via this - https://github.com/containscafeine/data-model/pull/21
